"""Y-data Profiling Check point 1

Checkpoint Objective
In this checkpoint, we are going to work on 'Education Attainment And Enrolment Around The World' dataset, provided by the World bank group.

Dataset description : The dataset was derived from the original copy, which was published on the world bank website. The primary purpose of this database is to document and analyse patterns of educational attainment rates in different country around the world.

➡ Dataset link


Columns description : 

Age[15-49]All_gradeX : Percentage of the entire population ages 15 to 49 that has completed grade X
Age[15-49]Male_gradeX : Percentage of the male population ages 15 to 49 that has completed grade X
Age[15-49]Female_gradeX : Percentage of the female population ages 15 to 49 that has completed grade X
X = [1...3]
Instructions
Step 1: Data exploration with Pandas
Download the provided dataset
Use pandas to read the file into a pandas Dataframe.
Display general information about the dataset.
Run descriptive analysis on the dataset using the 'describe' function.
Step 2: Data exploration with ydata-profiling
Use ydata-profiling to generate a report of the provided dataset.
Look for missing values in the dataset. You can use the report generated by ydata to identify missing values.
Examine the correlations between different columns in the dataset. You can use the report generated by ydata to identify correlations.
Identify any other interesting patterns or insights in the dataset that you can discover through the ydata-profiling report.
Step 3: Summary
Write a summary of your findings based on the ydata-profiling report. Be sure to include any interesting patterns or insights you discovered in the dataset.

Evaluation Specifics

Your instructor will evaluate your checkpoint based on the criterias mentioned below. All criteria are rated from 0 to 5

 Checkpoint Criteria

Successfully load the CSV file into a pandas dataframe
Successfully explore the data frame using pandas utilities
Successfully install and import the ydata-profiling
Successfully create the ydata-profiling report
Successfully interpret the report findings
Checkpoint Assessment

Technical mastery
Work quality
Problem resolution
Deadline ( If not respected , automatically score is 0 )"""

import pandas as pd 
import sweetviz as sv
#from ydata_profiling import ProfileReport
data="C:/Users/iyino/OneDrive/Documents/data science/Creating-a-Calculator-Program/tutorials/Data-Science-Tutorial-Programs/Dataset/edu_attainment.csv"
dataset = pd.read_csv(data)

data_info = dataset.info()
print(data_info)
data_describe = dataset.describe(include = "all")

myreport = sv.analyze(dataset)
myreport.show_html()

#profile = ProfileReport(dataset,title = ("profilingreport")
#profile.to_notebook_iframe()
missing = dataset.isnull().sum().sum()#missing values = 18
corr_1 = dataset.iloc[ :, 0 ].corr(dataset.iloc[:, 1])
corr_2 = dataset.iloc[:,2].corr(dataset.iloc[:,3])

#most of the colunns is highly corollated  directly a positive manner
 












